"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var shape = new Shape_1.Shape(5, 10);
var cirlce = new Circle_1.Circle(5, 10, 20);
var rectangle = new Rectangle_1.Rectangle(5, 10, 10, 20);
console.log(shape.getInfor());
console.log(cirlce.getInfor());
console.log(rectangle.getInfor());
